config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  match 'about', to: 'main#new', via: :get
  match 'hello', to: 'main#hello', via: :get
  match 'signup', to: 'registration#new', via: :get
  post 'signup', to: 'registration#create'
  match 'login', to: 'session#new', via: :get
  post 'login', to: 'session#login'
  delete 'logout', to: 'session#destroy'

  patch 'tasks/:id/toggle_complete', to: 'tasks#toggle_complete', as: :complete

  get 'main/index'

  resources :categories do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end
  # get 'tasks/index'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/show'
  # get 'tasks/delete'

  # get 'categories/index'
  # get 'categories/show'
  # get 'categories/new'
  # get 'categories/edit'
  # get 'categories/delete'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :tasks

  def self.get_category(name)
    Category.find_by(name:)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  #   has_secure_password
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def logged_in
    user_session = session[:user_id].present?
    redirect_to('/login') unless user_session
    user_session
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:id)
  end

  def show
    @categories = Category.find(params[:id])
    @tasks = @categories.tasks
  end

  def new
    @category = Category.new
  end

  def create
    category_params = params.require(:category).permit(:name)
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render('new')
    end
  end

  def edit; end

  def update; end

  def delete; end

  def destroy; end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    logged_in
    @logged_user = cookies[:user]
  end

  def about
    @created_by = 'Lucas Temponi'
    @id = params[:id]
    @page = params[:page]
  end

  def hello
    redirect_to(action: 'index')
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path
    else
      render('new')
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @user = User.new
  end

  def login
    @user = User.find_by(email: user_params[:email])

    if @user && @user.password == user_params[:password]
      session[:user_id] = @user.id
      cookies[:user] = @user[:email]
      flash[:notice] = 'Successfully logged in!'
      redirect_to('/')
    else
      render('new')
    end
  end

  def destroy
    cookies.delete(:user)
    session[:user_id] = nil
    redirect_to('/login')
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in

  def index
    @tasks = Task.order(:position)
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.order(:id) || []
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @count = Task.count
    @task = Task.new(position: @count + 1)
    @categories = Category.order(:id) || []
  end

  def create
    puts(params)
    @task = Task.new(task_params)
    @category = Category.find(task_params[:category_id])
    if @task.save
      @category.tasks << @task
      redirect_to tasks_path
    else
      render('new')
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render('edit')
    end
  end

  def toggle_complete
    @task = Task.find(params[:id])
    @task.update(completed: !@task.completed)
  end

  def delete; end

  def destroy; end

  private

  def task_params
    params.require(:task).permit(:name, :position, :completed, :description, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<div class='flex flex-col justify-center p-8'>
  <%= link_to("Back to Homepage",{controller: 'main',action: 'index'})%><br/>
  <h1 class="text-3xl font-bold underline">Categories#index</h1>
  <div class='justify-center flex-col flex gap-4' >
    <table class='w-[max(700px,90vw)] mx-auto border-2 w- text-center border-red mt-2'>
      <th>#</th>
      <th>Name</th>
      <% @categories.each do |category|%>
        <tr>
          <th><%= category.id%></th>
          <th><%= link_to(category.name,category_path(category))%><br/>
          </th>
        </tr>
      <% end%>
    </table>
    <%= link_to("New category",{action: 'new'},class: 'border-2 w-40 flex justify-center hover:bg-red-50 rounded-sm' )%><br/>
  </div>
</div>

app/views/categories/new.html.erb
<div class='flex flex-col justify-center mx-auto'>
  <%= link_to('Back to list',categories_path)%>
  <h1 class="text-3xl font-bold underline mb-4">Create task</h1>
  <%= form_for(@category) do |f| %>
    <% # url: category_path, method: 'post' %>
    <table>
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name,:required=>true)%></td>
      </tr>
    </table>
    <button><%= f.submit('Criar nova categoria')%></button>
  <%end%>
</div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<%= @categories.name%>
<% @tasks.each do |task| %>
  <p>
    <%= link_to(task.name,{controller: 'tasks',action: 'show'})%><br/>
  </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagerPostgresql</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/about.html.erb
<h1 class>Task Manager</h1>
<p>Task Manager in Rails</p>
<%= @page%>
<p><%=@created_by%></p>

app/views/main/index.html.erb
<div class='flex flex-col w-screen p-4' >
  <h1>Hello <%= @logged_user%></h1>
  <nav class='flex flex-row justify-between' >
    <ul class='flex flex-row gap-2' >
      <li>
        <%= link_to("Categories",categories_path)%>
      </li>
      <li>
        <%= link_to("Tasks",tasks_path)%>
      </li>
    </ul>
    <button class='border border-orange-500 rounded-full h-8 w-8'></button>
  </nav>
</div>
<%= button_to('logout', logout_path,{method: :delete})%>

app/views/session/new.html.erb
<div class='flex flex-col sm:flex-row w-screen h-screen '>
  <div class='w-full sm:w-3/5 flex justify-center items-center h-[23.58vh] sm:h-screen bg-gradient-to-r from-indigo-500'>
    <div class='flex w-[min(600px,90%)] flex-col justify-center flex-wrap content-center lg:content-start'>
      <h1 class='text-[2.5rem] font-bold text-white'>TaskManager</h1>
      <h4 class='text-lg mb-6 font-medium text-white'>Um projeto bobo usando rails</h4>
      <%= link_to('Read More','/about', :class=> "class:' w-[8.44rem] bg-[#0575E6] text-sm py-2 px-[1.88rem] cursor-pointer rounded-3xl hover:bg-[#045cb4]' hidden sm:block text-white" )%>
    </div>
    <svg class='absolute hidden sm:block bottom-0 left-0' width="431" height="280" viewBox="0 0 431 280" fill="none" xmlns="http://www.w3.org/2000/svg">
      <circle cx="152.5" cy="304.5" r="278" stroke="#0575E6"/>
      <circle cx="71.5" cy="278.5" r="278" stroke="#0575E6"/>
    </svg>
  </div>
  <div class='w-full h-full flex-col flex justify-center items-center sm:w-2/5' >
    <div class='flex justify-center flex-col w-[min(19.2rem,90%)]' >
      <h2 class= 'text-[1.625rem] font-bold'>Login</h2>
      <h3 class='text-lg font-normal mb-[2.44rem] ' >Entre ou <%= link_to('faça seu cadastro','/signup',:class => 'text-lg font-semibold text-[#0575E6]')%></h3>
      <%= form_with model: @user, url: login_path do |f| %>
        <div class='mb-4 flex items-center relative max-w-full w-80' >
          <svg class='absolute pointer-events-none ml-[1.62rem]' width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g opacity="0.3">
              <path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 5.25L2.25 4.5H21.75L22.5 5.25V18.75L21.75 19.5H2.25L1.5 18.75V5.25ZM3 6.8025V18H21V6.804L12.465 13.35H11.55L3 6.8025ZM19.545 6H4.455L12 11.8035L19.545 6Z" fill="#333333"/>
            </g>
          </svg>
          <%= f.text_field(:email,:required=>true,:class=>'border border-[#EEE] rounded-3xl focus:border-[#0575E6] focus:outline-none py-[1.12rem] pl-[3.62rem] pr-[1.62rem] w-full',:placeholder=>'Email')%>
        </div>
        <div class='mb-4 flex items-center relative max-w-full w-80' >
          <svg class='absolute pointer-events-none ml-[1.62rem]' width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <g opacity="0.3">
              <path d="M20 12C20 10.897 19.103 10 18 10H17V7C17 4.243 14.757 2 12 2C9.243 2 7 4.243 7 7V10H6C4.897 10 4 10.897 4 12V20C4 21.103 4.897 22 6 22H18C19.103 22 20 21.103 20 20V12ZM9 7C9 5.346 10.346 4 12 4C13.654 4 15 5.346 15 7V10H9V7Z" fill="#333333"/>
            </g>
          </svg>
          <%= f.password_field(:password,:required=>true,:class=>'border border-[#EEE] rounded-3xl focus:border-[#0575E6] focus:outline-none py-[1.12rem] pl-[3.62rem] pr-[1.62rem] w-full',:placeholder=>'Senha')%>
        </div>
        <%= f.submit('Entrar',class:'border bg-[#0575E6] text-sm w-full mb-4 py-[1.12rem] px-[1.62rem] cursor-pointer rounded-3xl hover:bg-[#045cb4]')%>
      <%end%>
      <%= link_to('Esqueceu sua senha','/signup',:class => 'text-sm mx-auto')%>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<table>
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name)%></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.text_field(:position)%></td>
  </tr>
  <tr>
    <th>Completed</th>
    <td><%= f.check_box(:completed)%></td>
  </tr>
  <tr>
    <th>Description</th>
    <td><%= f.text_area(:description)%></td>
  </tr>
  <tr>
    <th>Category</th>
    <td><%= f.select :category_id, categories.map { |category| [category.name,category.id] }, :include_blank => true  %></td>
  </tr>
</table>
<button><%= f.submit(button_label)%></button>

app/views/tasks/edit.html.erb
<div>
  <%= link_to('Back to list',tasks_path)%>
  <h1 class="text-3xl font-bold underline">Edit task</h1>
  <%= form_with model: @task do |f| %>
    <% # url: tasks_path(@task), method: 'patch' %>
    <%= render(partial: 'form',locals: ({f: f,button_label: 'Edit task',categories: @categories}))%>
  <%end%>
</div>

app/views/tasks/index.html.erb
<div class='flex gap-2 flex-col'>
  <%= link_to("Back to Homepage",{controller: 'main',action: 'index'})%><br/>
  <h1 class="text-3xl font-bold underline" >Tasks#index</h1>
  <%= button_to("Add new task",{action: 'new'})%><br/>
  <table class='w-[max(700px,90vw)] text-center mt-2'>
    <tr>
      <th>#</th>
      <th class='text-teal-700'>Task</th>
      <th>Completed</th>
      <th>Category</th>
      <th>Action</th>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <td><%=task.position%></td>
        <td><%=task.name%></td>
        <td>
          <%= form_with(model: task, url: complete_path(task)) do |f|%>
            <%= f.check_box :completed, { onchange: 'this.form.submit();' }%>
          <%end%>
          <td><%=task.category&.name || '-' %></td>
          <td>
            <%= link_to("Show",task_path(task), class: 'text-teal-500') %>
            <%= link_to("Edit", edit_task_path(task), class: 'text-teal-500') %>
            <%= link_to("Show","#", class: 'text-teal-500') %>
          </td>
        </tr>
      <% end %>
    </table>
    <%= link_to("New task",{action: 'new'},class: 'border-2 w-40 flex justify-center hover:bg-red-50 rounded-sm' )%><br/>
  </div>

app/views/tasks/new.html.erb
<div>
  <%= link_to('Back to list',tasks_path)%>
  <h1 class="text-3xl font-bold underline">Create task</h1>
  <%= form_for(@task) do |f| %>
    <% # url: tasks_path, method: 'post' %>
    <%= render(partial: 'form',locals: ({f: f,button_label: 'Create task',categories: @categories}))%>
  <%end%>
</div>

app/views/tasks/show.html.erb
<%= link_to('Back to list',tasks_path)%>
<%= link_to('Edit task',edit_task_path(@task))%>
<%= @task.name%>
<%= @task.description%>